<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/7/25
 * Time: 1:14
 */

namespace Home\Controller;

use Think\Controller\RestController;

class BaseController extends RestController
{
    private $PAGE_NO_EXIT;
    private $OBJECT_NOT_FOUNT;
    private $SUCCESS;
    private $FAIL;
    private $userModel;
    private $lessonModel;
    private $lessonTypeModel;
    private $studylogModel;
    private $paylogModel;
    private $videosModel;
    private $discussModel;
    private $wx_getOpenUrl;
    private $wx_token;
    private $pageSize;

    /**
     * @return mixed
     */
    public function getPageSize()
    {
        return $this->pageSize = 10;
    }

    /**
     * @return mixed
     */
    public function getWxToken()
    {
        return $this->wx_token = md5(time() . rand(0, 999) . 'qiyeclass');;
    }


    /**
     * @return array
     */
    public function getPAGENOEXIT()
    {
        return $this->PAGE_NO_EXIT = array('code' => 404, 'Msg' => '找不到页面啦', 'status' => 'fail');
    }

    /**
     * @return array
     */
    public function getOBJECTNOTFOUNT()
    {
        return $this->OBJECT_NOT_FOUNT = array('code' => 500, 'Msg' => '找不到对象', 'status' => 'fail');
    }

    /**
     * @return array
     */
    public function getSUCCESS()
    {
        return $this->SUCCESS = array('code' => 200, 'Msg' => '操作成功!', 'status' => 'success');
    }

    /**
     * @return array
     */
    public function getFAIL()
    {
        return $this->FAIL = array('code' => 300, 'Msg' => '操作失败!', 'status' => 'fail');
    }

    /**
     * @return mixed
     */
    public function getUserModel()
    {
        return $this->userModel = M('user');
    }

    /**
     * @return mixed
     */
    public function getLessonModel()
    {
        return $this->lessonModel = M('lesson');
    }

    /**
     * @return mixed
     */
    public function getLessonTypeModel()
    {
        return $this->lessonTypeModel = M('lessonType');
    }

    /**
     * @return mixed
     */
    public function getStudylogModel()
    {
        return $this->studylogModel = M('studylog');
    }

    /**
     * @return mixed
     */
    public function getPaylogModel()
    {
        return $this->paylogModel = M('paylog');
    }

    /**
     * @return mixed
     */
    public function getVideosModel()
    {
        return $this->videosModel = M('videos');
    }

    /**
     * @return mixed
     */
    public function getDiscussModel()
    {
        return $this->discussModel = M('discuss');
    }

    /**
     * @return string_URl
     */
    public function getWxGetOpenUrl()
    {
        return $this->wx_getOpenUrl = 'https://api.weixin.qq.com/sns/jscode2session?appid=APPID&secret=SECRET&js_code=JSCODE&grant_type=authorization_code';
    }

    protected function response($data, $flag = true, $type = 'json', $code = 200)
    {
        if ($flag) {
            $data['status'] = 'success';
            $data['code'] = 200;
        } else {
            $data['status'] = 'fail';
            $data['code'] = 502;
        }
        parent::response($data, $type, $code); // TODO: Change the autogenerated stub
    }
}