<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/7/25
 * Time: 1:14
 */

namespace Home\Controller;

use Think\Controller\RestController;

class BaseController extends RestController
{
    protected $PAGE_NO_EXIT;
    protected $OBJECT_NOT_FOUNT;
    protected $SUCCESS;
    protected $FAIL;
    protected $userModel;
    protected $lessonModel;
    protected $lessonTypeModel;
    protected $studylogModel;
    protected $paylogModel;
    protected $videosModel;
    protected $discussModel;
    protected $wx_getOpenUrl;
    protected $wx_token;

    /**
     * @return mixed
     */
    public function getWxToken()
    {
        return md5(time() . rand(0, 999) . 'qiyeclass');;
    }

    protected function response($data, $type = 'json', $code = 200)
    {
        parent::response($data, $type, $code); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    public function getPAGENOEXIT()
    {
        return array('code' => 404, 'Msg' => '找不到页面啦', 'status' => 'fail');
    }

    /**
     * @return array
     */
    public function getOBJECTNOTFOUNT()
    {
        return array('code' => 500, 'Msg' => '找不到对象', 'status' => 'fail');
    }

    /**
     * @return array
     */
    public function getSUCCESS()
    {
        return array('code' => 200, 'Msg' => '操作成功!', 'status' => 'success');
    }

    /**
     * @return array
     */
    public function getFAIL()
    {
        return array('code' => 300, 'Msg' => '操作失败!', 'status' => 'fail');
    }

    /**
     * @return mixed
     */
    public function getUserModel()
    {
        return M('user');
    }

    /**
     * @return mixed
     */
    public function getLessonModel()
    {
        return M('lesson');
    }

    /**
     * @return mixed
     */
    public function getLessonTypeModel()
    {
        return M('lessonType');
    }

    /**
     * @return mixed
     */
    public function getStudylogModel()
    {
        return M('studylog');
    }

    /**
     * @return mixed
     */
    public function getPaylogModel()
    {
        return M('paylog');
    }

    /**
     * @return mixed
     */
    public function getVideosModel()
    {
        return M('videos');
    }

    /**
     * @return mixed
     */
    public function getDiscussModel()
    {
        return M('discuss');
    }

    /**
     * @return string_URl
     */
    public function getWxGetOpenUrl()
    {
        return 'https://api.weixin.qq.com/sns/jscode2session?appid=APPID&secret=SECRET&js_code=JSCODE&grant_type=authorization_code';
    }

}